services:
  db:
    container_name: db
    image: postgres:15-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - sleep-stack

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "sample@gmail.com.br"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "50100:80"
    depends_on:
      - db
    networks:
      - sleep-stack

  sleep_api:
    container_name: sleep_api
    build: ./sleep/
    volumes:
      - ./sleep/:/sleep/ 
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USER=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
    networks:
      - sleep-stack


networks:
  sleep-stack:

volumes:
  db:
