services:
  db:
    container_name: db
    image: postgres:15-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - sleep-stack

  sleep_api:
    container_name: sleep_api
    build: ./sleep/
    volumes:
      - ./sleep/:/sleep/ 
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USER=user
      - SPRING_DATASOURCE_PASSWORD=password
    restart: on-failure
    depends_on:
      - db
    networks:
      - sleep-stack


networks:
  sleep-stack:

volumes:
  db:
